name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  TestSolution:
    runs-on: windows-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v4
       - 
        name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
       -
        name: Restore with dotnet
        run: dotnet restore
       - 
        name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
       - 
        name: Run Tests
        run: dotnet test --no-restore
  
  BuildAndPushDockerImage:
    runs-on: windows-latest
    needs: TestSolution
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gabrieletoffanin/pokefun:latest
