name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  TestSolution:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v4
       - 
        name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
       -
        name: Restore with dotnet
        run: dotnet restore ./PokeFun
       - 
        name: Build with dotnet
        run: dotnet build ./PokeFun/src/PokeFun.Api/PokeFun.Api.csproj --configuration Release --no-restore
       - 
        name: Test RecipesController
        run: dotnet test ./PokeFun/tst/PokeFun.Application.Tests --no-restore
  
  BuildAndPushDockerImage:
    runs-on: ubuntu-latest
    needs: TestSolution
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gabrieletoffanin/pokefun:latest
